AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: High stress scanning API with alerts.

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        DB_NAME: "records"
        DB_USER: !Ref DbUser
        DB_PASSWORD: !Sub "{{resolve:secretsmanager:${DbSecretArn}:SecretString:password}}"
        DB_HOST: !Ref DbHost
        DB_PORT: !Ref DbPort

Parameters:
  DbUser:
    Type: String
    Description: Database username
  DbHost:
    Type: String
    Description: Database endpoint (hostname)
  DbPort:
    Type: String
    Default: 5432
    Description: Database port
  DbSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret with DB credentials

Resources:

  ### Python lambda for file scanning agent
  Agent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: py-lambda/
      Handler: agent.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref DbSecretArn
      Events:
        ApiGet:
          Type: Api
          Properties:
            Path: /agent
            Method: post
      VpcConfig:
        SecurityGroupIds:
          - sg-lambda
        SubnetIds:
          - subnet-xxx

  ### Python lambda for reading alerts
  Alerts:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: py-lambda/
      Handler: alerts.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref DbSecretArn
      Events:
        ApiGet:
          Type: Api
          Properties:
            Path: /alerts
            Method: post
      VpcConfig:
        SecurityGroupIds:
          - sg-lambda
        SubnetIds:
          - subnet-xxx

Outputs:
  AgentApiUrl:
    Description: "Agent API endpoint"
    Value:
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/agent"

  AlertsApiUrl:
    Description: "Alerts API endpoint"
    Value:
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/alerts"
